### ISSUE TITLE
[0031] [ndf-script] [bug] None screenshot value

### ISSUE THREAD

**Issue by Dovahgamer** [greg-ynx/NexusDownloadFlow#14]
Trying to use NDF2.0.0 with Wabbajack, sadly it doesn't click on slow download, rather it clicks on the "Click here" text after I manually click slow download.
Older Logfile is included.
[2023_11_21_ndf.log](https://github.com/greg-ynx/NexusDownloadFlow/files/13428623/2023_11_21_ndf.log)

**Comment by greg-ynx** [comment]
Hi! Sorry for this bug, I'll fix it as fast as I can, can you provide more information? I would like to know if your using the .exe version or if your are running NDF using your python interpreter? Do you have multiple monitors? And what is your resolution for each one of them?
Finally, did NDF clicked at least once since you've downloaded it?

Thank you for reporting this issue and for providing the log file. 🙂

**Comment by Dovahgamer** [comment]
Hi there, thanks for the quick response!
I'm using the .exe. I have two monitors, both are 1920x1080.
NDF has clicked before, but only on the Click here text, not the Slow Download button.

If you need more recent logfiles, let me know.

**Comment by greg-ynx** [comment]
I reproduced your bug on my side, after 3 mods downloaded, NDF no longer clicked on the 4th open page. I couldn't click on it manually either, so I had to reload the page for the script to work again. I think this bug is caused by clicking too quickly on the `slow download` button and then on the `click here` button.

I'm working on a fix, and version 2.0.1 will be delivered with this bug corrected.

For now, the only solution is to refresh the page manually. If NDF still doesn't click after this, I suggest you use version [2022v1.0.0](https://github.com/greg-ynx/NexusDownloadFlow/releases/tag/2022v1.0.0) and take screenshots of the `Slown Download` and `Click here` buttons on your side.

Best regards,
Greg

**Comment by greg-ynx** [comment]
Hi! I currently can't reproduce your issue (I do not have any exception occuring in my logfile). Have you tried to download a modlist with NDF recently? I would like to know if this bug is still active.

**Comment by greg-ynx** [comment]
I cannot replicate the `not clicking` issue but I will fix the error raised in your logfile. Becareful I saw that nothing happen when you click on the `slow download` button after clicking on the `mod manager download` button if you don't have any compatible mod manager with Nexus mods. This might be why NDF logs that you clicked but nothing happens.

**Comment by greg-ynx** [comment]
Fix pushed to 2.0.1 version
